(cl:defpackage rbx2_utils-srv
  (:use )
  (:export
   "OLDLAUNCHPROCESS"
   "<OLDLAUNCHPROCESS-REQUEST>"
   "OLDLAUNCHPROCESS-REQUEST"
   "<OLDLAUNCHPROCESS-RESPONSE>"
   "OLDLAUNCHPROCESS-RESPONSE"
   "KILLPROCESS"
   "<KILLPROCESS-REQUEST>"
   "KILLPROCESS-REQUEST"
   "<KILLPROCESS-RESPONSE>"
   "KILLPROCESS-RESPONSE"
   "LAUNCHPROCESS"
   "<LAUNCHPROCESS-REQUEST>"
   "LAUNCHPROCESS-REQUEST"
   "<LAUNCHPROCESS-RESPONSE>"
   "LAUNCHPROCESS-RESPONSE"
  ))

