// Generated by gencpp from file rbx2_utils/KillProcess.msg
// DO NOT EDIT!


#ifndef RBX2_UTILS_MESSAGE_KILLPROCESS_H
#define RBX2_UTILS_MESSAGE_KILLPROCESS_H

#include <ros/service_traits.h>


#include <rbx2_utils/KillProcessRequest.h>
#include <rbx2_utils/KillProcessResponse.h>


namespace rbx2_utils
{

struct KillProcess
{

typedef KillProcessRequest Request;
typedef KillProcessResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct KillProcess
} // namespace rbx2_utils


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rbx2_utils::KillProcess > {
  static const char* value()
  {
    return "54319f819462371f5e2b56e424d9b26f";
  }

  static const char* value(const ::rbx2_utils::KillProcess&) { return value(); }
};

template<>
struct DataType< ::rbx2_utils::KillProcess > {
  static const char* value()
  {
    return "rbx2_utils/KillProcess";
  }

  static const char* value(const ::rbx2_utils::KillProcess&) { return value(); }
};


// service_traits::MD5Sum< ::rbx2_utils::KillProcessRequest> should match 
// service_traits::MD5Sum< ::rbx2_utils::KillProcess > 
template<>
struct MD5Sum< ::rbx2_utils::KillProcessRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rbx2_utils::KillProcess >::value();
  }
  static const char* value(const ::rbx2_utils::KillProcessRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rbx2_utils::KillProcessRequest> should match 
// service_traits::DataType< ::rbx2_utils::KillProcess > 
template<>
struct DataType< ::rbx2_utils::KillProcessRequest>
{
  static const char* value()
  {
    return DataType< ::rbx2_utils::KillProcess >::value();
  }
  static const char* value(const ::rbx2_utils::KillProcessRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rbx2_utils::KillProcessResponse> should match 
// service_traits::MD5Sum< ::rbx2_utils::KillProcess > 
template<>
struct MD5Sum< ::rbx2_utils::KillProcessResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rbx2_utils::KillProcess >::value();
  }
  static const char* value(const ::rbx2_utils::KillProcessResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rbx2_utils::KillProcessResponse> should match 
// service_traits::DataType< ::rbx2_utils::KillProcess > 
template<>
struct DataType< ::rbx2_utils::KillProcessResponse>
{
  static const char* value()
  {
    return DataType< ::rbx2_utils::KillProcess >::value();
  }
  static const char* value(const ::rbx2_utils::KillProcessResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RBX2_UTILS_MESSAGE_KILLPROCESS_H
