// Generated by gencpp from file rbx2_msgs/SetBatteryLevelResponse.msg
// DO NOT EDIT!


#ifndef RBX2_MSGS_MESSAGE_SETBATTERYLEVELRESPONSE_H
#define RBX2_MSGS_MESSAGE_SETBATTERYLEVELRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rbx2_msgs
{
template <class ContainerAllocator>
struct SetBatteryLevelResponse_
{
  typedef SetBatteryLevelResponse_<ContainerAllocator> Type;

  SetBatteryLevelResponse_()
    {
    }
  SetBatteryLevelResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }






  typedef boost::shared_ptr< ::rbx2_msgs::SetBatteryLevelResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rbx2_msgs::SetBatteryLevelResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetBatteryLevelResponse_

typedef ::rbx2_msgs::SetBatteryLevelResponse_<std::allocator<void> > SetBatteryLevelResponse;

typedef boost::shared_ptr< ::rbx2_msgs::SetBatteryLevelResponse > SetBatteryLevelResponsePtr;
typedef boost::shared_ptr< ::rbx2_msgs::SetBatteryLevelResponse const> SetBatteryLevelResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rbx2_msgs::SetBatteryLevelResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rbx2_msgs::SetBatteryLevelResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rbx2_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rbx2_msgs::SetBatteryLevelResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rbx2_msgs::SetBatteryLevelResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rbx2_msgs::SetBatteryLevelResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rbx2_msgs::SetBatteryLevelResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rbx2_msgs::SetBatteryLevelResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rbx2_msgs::SetBatteryLevelResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rbx2_msgs::SetBatteryLevelResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::rbx2_msgs::SetBatteryLevelResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::rbx2_msgs::SetBatteryLevelResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rbx2_msgs/SetBatteryLevelResponse";
  }

  static const char* value(const ::rbx2_msgs::SetBatteryLevelResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rbx2_msgs::SetBatteryLevelResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::rbx2_msgs::SetBatteryLevelResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rbx2_msgs::SetBatteryLevelResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetBatteryLevelResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rbx2_msgs::SetBatteryLevelResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::rbx2_msgs::SetBatteryLevelResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // RBX2_MSGS_MESSAGE_SETBATTERYLEVELRESPONSE_H
