// Generated by gencpp from file rbx2_msgs/SetBatteryLevel.msg
// DO NOT EDIT!


#ifndef RBX2_MSGS_MESSAGE_SETBATTERYLEVEL_H
#define RBX2_MSGS_MESSAGE_SETBATTERYLEVEL_H

#include <ros/service_traits.h>


#include <rbx2_msgs/SetBatteryLevelRequest.h>
#include <rbx2_msgs/SetBatteryLevelResponse.h>


namespace rbx2_msgs
{

struct SetBatteryLevel
{

typedef SetBatteryLevelRequest Request;
typedef SetBatteryLevelResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetBatteryLevel
} // namespace rbx2_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rbx2_msgs::SetBatteryLevel > {
  static const char* value()
  {
    return "0aca93dcf6d857f0e5a0dc6be1eaa9fb";
  }

  static const char* value(const ::rbx2_msgs::SetBatteryLevel&) { return value(); }
};

template<>
struct DataType< ::rbx2_msgs::SetBatteryLevel > {
  static const char* value()
  {
    return "rbx2_msgs/SetBatteryLevel";
  }

  static const char* value(const ::rbx2_msgs::SetBatteryLevel&) { return value(); }
};


// service_traits::MD5Sum< ::rbx2_msgs::SetBatteryLevelRequest> should match 
// service_traits::MD5Sum< ::rbx2_msgs::SetBatteryLevel > 
template<>
struct MD5Sum< ::rbx2_msgs::SetBatteryLevelRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rbx2_msgs::SetBatteryLevel >::value();
  }
  static const char* value(const ::rbx2_msgs::SetBatteryLevelRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rbx2_msgs::SetBatteryLevelRequest> should match 
// service_traits::DataType< ::rbx2_msgs::SetBatteryLevel > 
template<>
struct DataType< ::rbx2_msgs::SetBatteryLevelRequest>
{
  static const char* value()
  {
    return DataType< ::rbx2_msgs::SetBatteryLevel >::value();
  }
  static const char* value(const ::rbx2_msgs::SetBatteryLevelRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rbx2_msgs::SetBatteryLevelResponse> should match 
// service_traits::MD5Sum< ::rbx2_msgs::SetBatteryLevel > 
template<>
struct MD5Sum< ::rbx2_msgs::SetBatteryLevelResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rbx2_msgs::SetBatteryLevel >::value();
  }
  static const char* value(const ::rbx2_msgs::SetBatteryLevelResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rbx2_msgs::SetBatteryLevelResponse> should match 
// service_traits::DataType< ::rbx2_msgs::SetBatteryLevel > 
template<>
struct DataType< ::rbx2_msgs::SetBatteryLevelResponse>
{
  static const char* value()
  {
    return DataType< ::rbx2_msgs::SetBatteryLevel >::value();
  }
  static const char* value(const ::rbx2_msgs::SetBatteryLevelResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RBX2_MSGS_MESSAGE_SETBATTERYLEVEL_H
